export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MSG = 'CHANGE_MSG';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPDATE_QUANTITY_PRODUCT_IN_CART = 'UPDATE_QUANTITY_PRODUCT_IN_CART';
